name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: github.repository == 'imbsky/dvm'

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [13.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Install libcurl4-openssl-dev package for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libcurl4-openssl-dev

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install esy
        run: npm install --global esy

      - name: Install and build OCaml packages
        run: esy

      - name: Build
        run: esy build

      - name: Copy and rename binary
        run: cp _build/default/src/dvm.exe ./dvm

      - name: Prepare release asset
        run: tar -zcvf dvm-x86_64-${{ matrix.os }}.tar.gz dvm

      - name: Create release
        uses: softprops/action-gh-release@v0.1.4
        with:
          files: dvm-x86_64-${{ matrix.os }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
