name: Main workflow

on:
  push:
  pull_request:

jobs:
  build:
    if: github.repository == 'imbsky/dvm'

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [13.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install libcurl4-openssl-dev package for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libcurl4-openssl-dev

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install esy
        run: npm install --global esy

      - name: Restore esy cache
        uses: actions/cache@v1
        with:
          path: ~/.esy
          key: ${{ runner.os }}-esy-${{ hashFiles(format('{0}{1}', github.workspace, '/esy.lock/index.json')) }}

      - name: Install and build OCaml packages
        run: esy

      - name: Build
        run: esy build

      - name: Copy and rename binary
        run: cp _esy/default/build/default/src/dvm.exe ./dvm

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v1
        with:
          name: dvm-${{ matrix.os }}
          path: dvm
